package resourceprompts

import (
	"fmt"

	"github.com/g14a/tf/builder"
	"github.com/g14a/tf/types"
	"github.com/g14a/tf/validators"

	"github.com/fatih/color"
	"github.com/manifoldco/promptui"
)

func AWSAPIGatewayAccountPrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	schema := []types.Schema{
		{
			Field: "cloudwatch_role_arn",
			Ex:    "",
			Doc: "(Optional) The ARN of an IAM role for CloudWatch (to allow logging & monitoring). " +
				"\nCheckout https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-stage-settings.html#how-to-stage-settings-console " +
				"\nLogging & monitoring can be enabled/disabled and otherwise tuned on the API Gateway Stage level.",
		},
	}

	resourceBlock := builder.PSOrder(types.ProvidePS(schema))

	builder.ResourceBuilder("aws_api_gateway_account", blockName, resourceBlock)
}

func AWSAPIGatewayApiKeyPrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	schema := []types.Schema{
		{
			Field: "name",
			Ex:    "",
			Doc:   "(Required) The name of the API key",
		},
		{
			Field: "description",
			Ex:    "",
			Doc:   "(Optional) The API key description. Defaults to \"Managed by Terraform\".",
		},
		{
			Field:     "enabled",
			Ex:        "(true/false)",
			Doc:       "(Optional) Specifies whether the API key can be used by callers. Defaults to true.",
			Validator: validators.BoolValidator,
		},
		{
			Field: "value",
			Ex:    "api-key-123",
			Doc:   "(Optional) The value of the API key. If not specified, it will be automatically generated by AWS on creation.",
		},
		{
			Field: "tags",
			Ex:    "k1=v1,k2=v2",
			Doc:   "(Optional) Key-value map of resource tags",
		},
	}

	resourceBlock := builder.PSOrder(types.ProvidePS(schema))

	builder.ResourceBuilder("aws_api_gateway_api_key", blockName, resourceBlock)
}

func AWSAPIGatewayAuthorizerPrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	schema := []types.Schema{
		{
			Field: "name",
			Ex:    "auth-name-123",
			Doc:   "(Required) The name of the authorizer",
		},
		{
			Field: "rest_api_id",
			Ex:    "rai-123",
			Doc:   "(Required) The ID of the associated REST API",
		},
		{
			Field: "identity_source",
			Ex:    "",
			Doc: "(Optional) The source of the identity in an incoming request. Defaults to method.request.header.Authorization. " +
				"\nFor REQUEST type, this may be a comma-separated list of values, including headers, query string parameters and stage variables - e.g. " +
				"\n\"method.request.header.SomeHeaderName,method.request.querystring.SomeQueryStringName,stageVariables.SomeStageVariableName\"",
		},
		{
			Type:  "select",
			Field: "type",
			Doc: "(Optional) The type of the authorizer. Possible values are TOKEN for a " +
				"\nLambda function using a single authorization token submitted in a " +
				"\ncustom header, REQUEST for a Lambda function using incoming request " +
				"\nparameters, or COGNITO_USER_POOLS for using an Amazon Cognito user pool. " +
				"\nDefaults to TOKEN",
			Items: []string{"TOKEN", "REQUEST", "COGNITO_USER_POOLS"},
		},
		{
			Field: "authorizer_credentials",
			Ex:    "",
			Doc: "(Optional) The credentials required for the authorizer. To specify an IAM Role for API Gateway " +
				"\nto assume, use the IAM Role ARN.",
		},
		{
			Field:     "authorizer_result_ttl_in_seconds",
			Ex:        "300",
			Doc:       "(Optional) The TTL of cached authorizer results in seconds. Defaults to 300",
			Validator: validators.IntValidator,
		},
		{
			Field: "identity_validation_expression",
			Ex:    "",
			Doc: "(Optional) A validation expression for the incoming identity. For TOKEN type, " +
				"\nthis value should be a regular expression. The incoming token from the client " +
				"\nis matched against this expression, and will proceed if the token matches. " +
				"\nIf the token doesn't match, the client receives a 401 Unauthorized response.",
		},
		{
			Field: "provider_arns",
			Ex:    "",
			Doc: "(Optional, required for type COGNITO_USER_POOLS) A list of the Amazon Cognito user pool ARNs. " +
				"\nEach element is of this format: arn:aws:cognito-idp:{region}:{account_id}:userpool/{user_pool_id}",
		},
	}

	resourceBlock := builder.PSOrder(types.ProvidePS(schema))

	builder.ResourceBuilder("aws_api_gateway_authorizer", blockName, resourceBlock)
}

func AWSAPIGatewayBasePathMappingPrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	schema := []types.Schema{
		{
			Field: "domain_name",
			Ex:    "",
			Doc:   "(Required) The already-registered domain name to connect the API to.",
		},
		{
			Field: "api_id",
			Ex:    "",
			Doc:   "(Required) The id of the API to connect.",
		},
		{
			Field: "stage_name",
			Ex:    "",
			Doc:   "(Optional) The name of a specific deployment stage to expose at the given path. If omitted, callers may select any stage by including its name as a path element after the base path.",
		},
		{
			Field: "base_path",
			Ex:    "",
			Doc:   "(Optional) Path segment that must be prepended to the path when accessing the API via this mapping. If omitted, the API is exposed at the root of the given domain.",
		},
	}

	resourceBlock := builder.PSOrder(types.ProvidePS(schema))

	builder.ResourceBuilder("aws_api_gateway_base_path_mapping", blockName, resourceBlock)
}

func AWSAPIGatewayClientCertificatePrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	schema := []types.Schema{
		{
			Field: "description",
			Ex:    "",
			Doc:   "(Optional) The description of the client certificate.",
		},
		{
			Field:     "tags",
			Ex:        "k1=v1,k2=v2",
			Doc:       "(Optional) Key-value map of resource tags",
			Validator: validators.RCValidator,
		},
	}

	resourceBlock := builder.PSOrder(types.ProvidePS(schema))

	builder.ResourceBuilder("aws_api_gateway_client_certificate", blockName, resourceBlock)
}

func AWSAPIGatewayDeploymentPrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	schema := []types.Schema{
		{
			Field: "rest_api_id",
			Ex:    "",
			Doc:   "(Required) The ID of the associated REST API",
		},
		{
			Field: "stage_name",
			Ex:    "",
			Doc:   "(Optional) The name of the stage. If the specified stage already exists, it will be updated to point to the new deployment. If the stage does not exist, a new one will be created and point to this deployment.",
		},
		{
			Field: "description",
			Ex:    "",
			Doc:   "(Optional) The description of the deployment",
		},
		{
			Field: "stage_description",
			Ex:    "",
			Doc:   "(Optional) The description of the stage",
		},
		{
			Field:     "tags",
			Ex:        "k1=v1,k2=v2",
			Doc:       "(Optional) Key-value map of resource tags",
			Validator: validators.RCValidator,
		},
		{
			Field:     "variables",
			Ex:        "k1=v1,k2=v2",
			Doc:       "(Optional) A map that defines variables for the stage",
			Validator: validators.RCValidator,
		},
	}

	resourceBlock := builder.PSOrder(types.ProvidePS(schema))

	builder.ResourceBuilder("aws_api_gateway_deployment", blockName, resourceBlock)
}

func AWSAPIGatewayDocumentationPartPrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	schema := []types.Schema{
		{
			Field: "properties",
			Ex:    "",
			Doc:   "(Required) A content map of API-specific key-value pairs describing the targeted API entity. The map must be encoded as a JSON string, e.g., \"{ \\\"description\\\": \\\"The API does …\\\" }\". Only Swagger-compliant key-value pairs can be exported and, hence, published.",
		},
		{
			Field: "rest_api_id",
			Ex:    "",
			Doc:   "(Required) The ID of the associated Rest API",
		},
	}

	resourceBlock := builder.PSOrder(types.ProvidePS(schema))

	color.Green("\nEnter location:\n(Required) The location of the targeted API entity of the to-be-created documentation part.\n" +
		"The location block supports:" +
		"\n1.method\n2.name\n3.path\n4.status_code\n5.type")

	locationSchema := []types.Schema{
		{
			Field: "method",
			Ex:    "",
			Doc:   "(Optional) The HTTP verb of a method. The default value is * for any method.",
		},
		{
			Field: "name",
			Ex:    "",
			Doc:   "(Optional) The name of the targeted API entity.",
		},
		{
			Field: "path",
			Ex:    "",
			Doc:   "(Optional) The URL path of the target. The default value is / for the root resource.",
		},
		{
			Field: "status_code",
			Ex:    "",
			Doc:   "(Optional) The HTTP status code of a response. The default value is * for any status code.",
		},
		{
			Type:  "select",
			Field: "type",
			Doc:   "(Required) The type of API entity to which the documentation content applies.",
			Items: []string{"API", "METHOD", "REQUEST_BODY"},
		},
	}

	resourceBlock["location"] = builder.PSOrder(types.ProvidePS(locationSchema))

	builder.ResourceBuilder("aws_api_gateway_documentation_part", blockName, resourceBlock)
}

func AWSAPIGatewayDocumentationVersionPrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	schema := []types.Schema{
		{
			Field: "version",
			Ex:    "",
			Doc:   "(Required) The version identifier of the API documentation snapshot.",
		},
		{
			Field: "rest_api_id",
			Ex:    "",
			Doc:   "(Required) The ID of the associated Rest API",
		},
		{
			Field: "description",
			Ex:    "",
			Doc:   "(Optional) The description of the API documentation version.",
		},
	}

	resourceBlock := builder.PSOrder(types.ProvidePS(schema))
	builder.ResourceBuilder("aws_api_gateway_documentation_version", blockName, resourceBlock)
}

// aws_api_gateway_domain_name
func AWSAPIGatewayDomainNamePrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	schema := []types.Schema{
		{
			Field: "domain_name",
			Ex:    "",
			Doc:   "(Required) The fully-qualified domain name to register",
		},
		{
			Field: "certificate_arn",
			Ex:    "",
			Doc: "(Optional) The ARN for an AWS-managed certificate. " +
				"\nAWS Certificate Manager is the only supported source. " +
				"\nUsed when an edge-optimized domain name is desired. " +
				"\nConflicts with certificate_name, certificate_body, " +
				"\ncertificate_chain, certificate_private_key, regional_certificate_arn," +
				"\nand regional_certificate_name.",
		},
		{
			Field: "regional_certificate_arn",
			Ex:    "",
			Doc: "(Optional) The ARN for an AWS-managed certificate. " +
				"\nAWS Certificate Manager is the only supported source. " +
				"\nUsed when a regional domain name is desired. Conflicts " +
				"\nwith certificate_arn, certificate_name, certificate_body, " +
				"\ncertificate_chain, and certificate_private_key",
		},
		{
			Field: "certificate_name",
			Ex:    "",
			Doc:   "(Optional) The unique name to use when registering this certificate as an IAM server certificate. Conflicts with certificate_arn, regional_certificate_arn, and regional_certificate_name. Required if certificate_arn is not set.",
		},
		{
			Field: "certificate_body",
			Ex:    "",
			Doc:   "(Optional) The certificate issued for the domain name being registered, in PEM format. Only valid for EDGE endpoint configuration type. Conflicts with certificate_arn, regional_certificate_arn, and regional_certificate_name",
		},
		{
			Field: "certificate_chain",
			Ex:    "",
			Doc:   "(Optional) The certificate for the CA that issued the certificate, along with any intermediate CA certificates required to create an unbroken chain to a certificate trusted by the intended API clients. Only valid for EDGE endpoint configuration type. Conflicts with certificate_arn, regional_certificate_arn, and regional_certificate_name",
		},
		{
			Field: "certificate_private_key",
			Ex:    "",
			Doc:   "(Optional) The private key associated with the domain certificate given in certificate_body. Only valid for EDGE endpoint configuration type. Conflicts with certificate_arn, regional_certificate_arn, and regional_certificate_name",
		},
		{
			Field: "regional_certificate_name",
			Ex:    "",
			Doc:   "(Optional) The user-friendly name of the certificate that will be used by regional endpoint for this domain name. Conflicts with certificate_arn, certificate_name, certificate_body, certificate_chain, and certificate_private_key.",
		},
		{
			Type:  "select",
			Field: "security_policy",
			Doc:   "(Optional) The Transport Layer Security (TLS) version + cipher suite for this DomainName. The valid values are TLS_1_0 and TLS_1_2. Must be configured to perform drift detection.",
			Items: []string{"TLS_1_0", "TLS_1_2"},
		},
	}

	resourceBlock := builder.PSOrder(types.ProvidePS(schema))

	color.Yellow("\nConfigure nested settings like endpoint_configuration/tags [y/n]?\n\n", "text")

	ynPrompt := promptui.Prompt{
		Label: "",
	}

	yn, err := ynPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	if yn == "n" || yn == "" {
		builder.ProviderBuilder("aws_api_gateway_domain_name", resourceBlock)
		return
	}

	endpointConfigSchema := []types.Schema{
		{
			Field: "types",
			Ex:    "",
			Doc: "(Required) A list of endpoint types. This resource currently only supports " +
				"\nmanaging a single value. Valid values: EDGE or REGIONAL. If unspecified, " +
				"\ndefaults to EDGE. Must be declared as REGIONAL in non-Commercial partitions. " +
				"\nRefer to the documentation for more information on the difference between " +
				"\nedge-optimized and regional APIs.",
			Items: []string{"EDGE", "REGIONAL"},
		},
	}

	resourceBlock["endpoint_configuration"] = builder.PSOrder(types.ProvidePS(endpointConfigSchema))
	builder.ResourceBuilder("aws_api_gateway_domain_name", blockName, resourceBlock)
}

func AWSAPIGatewayGatewayResponsePrompt() {
	color.Green("\nEnter block name(Required) e.g. foo/bar\n\n")
	blockPrompt := promptui.Prompt{
		Label: "",
	}

	blockName, err := blockPrompt.Run()
	if err != nil {
		fmt.Println(err)
	}

	prompts := map[string]types.TfPrompt{}
	var promptOrder []string

	prompts["rest_api_id"] = types.TfPrompt{
		Label: "Enter rest_api_id:\n(Required) The string identifier of the associated REST API.",
		Prompt: promptui.Prompt{
			Label: "",
		},
	}
	promptOrder = append(promptOrder, "rest_api_id")

	prompts["response_type"] = types.TfPrompt{
		Label: "Enter response_type:\n(Required) The response type of the associated GatewayResponse.",
		Prompt: promptui.Prompt{
			Label: "",
		},
	}
	promptOrder = append(promptOrder, "response_type")

	prompts["status_code"] = types.TfPrompt{
		Label: "Enter status_code:\n(Optional) The HTTP status code of the Gateway Response.",
		Prompt: promptui.Prompt{
			Label: "",
		},
	}
	promptOrder = append(promptOrder, "status_code")

	resourceBlock := builder.PSOrder(promptOrder, nil, prompts, nil)

	color.Green("\nEnter response_templates:\n(Optional) A map specifying the templates used to transform the response body.")

	responseTemplatesPrompt := map[string]types.TfPrompt{}
	var nestedPromptOrder []string

	responseTemplatesPrompt["application/json"] = types.TfPrompt{
		Label: "Enter application/json:\nCheck https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_gateway_response",
		Prompt: promptui.Prompt{
			Label: "",
		},
	}
	nestedPromptOrder = append(nestedPromptOrder, "application/json")

	resourceBlock["response_templates"] = builder.PSOrder(nestedPromptOrder, nil, responseTemplatesPrompt, nil)

	builder.ResourceBuilder("aws_api_gateway_account", blockName, resourceBlock)
}

func AWSAPIGatewayIntegration() {

}
